CREATE SCHEMA reservationschema;

CREATE TABLE reservations(
  id                    serial  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  reservation_number    bigint  NOT NULL UNIQUE ,
  date_of_reservation   date    NOT NULL,
  time_of_reservation   time    NOT NULL,
  amount_of_people      int     NOT NULL,
  CONSTRAINT pk_reservation_id PRIMARY KEY (id)
);